//{{NO_DEPENDENCIES}}
// Resource identifiers used by VirtualDimension.rc
//

// Menus
#define IDM_WALLPAPER_CTXMENU           4
#define IDM_SHORTCUTS_CTXMENU           101

// Dialogs
#define IDD_APPLLIST_DLG                101
#define IDD_TROUBLESHOOTING_SETTINGS    102
#define IDD_ABOUTBOX                    103
#define IDD_DESKS_SETTINGS              130
#define IDD_DESKTOPPROPS                131
#define IDD_WINDOW_SETTINGS             135
#define IDD_GLOBAL_SETTINGS             137
#define IDD_MOVEWINDOW                  138
#define IDD_WINDOW_AUTOSETTINGS         139
#define IDD_OSD_SETTINGS                140
#define IDD_DISPLAY_SETTINGS            141
#define IDD_SHORTCUT_SETTINGS           142
#define IDD_MOUSEWARP_SETTINGS          147

// Commands
#define IDM_ABOUT                       104
#define IDM_EXIT                        105
#define IDM_CONFIGURE                   106
#define IDM_LOCKPREVIEWWND              110
#define IDM_SHOWCAPTION                 111

// Icons and other resources
#define IDI_VIRTUALDIMENSION            107
#define IDI_DEFAPP_SMALL                108
#define IDC_VIRTUALDIMENSION            109
#define IDI_KILL                        143
#define IDI_MAXIMIZE_VERT               144
#define IDI_MAXIMIZE_HORIZ              145
#define IDR_LOGO                        300

// Strings
#define IDS_PROGRAM                     100
#define IDS_PROGRAMINLIST_ERROR         101
#define IDS_ERROR                       102
#define IDS_APP_TITLE                   161
#define IDS_ADDPROGRAM                  103
#define IDS_PROGRAMFILTER               104
#define IDS_PICTUREFILTER               105
#define IDS_SELECT_BACKGROUND           106
#define IDS_DISABLED                    107
#define IDS_PARAM_COLOR                 108
#define IDS_PARAM_IMAGE                 109
#define IDS_NEEDADESKTOP_ERROR          111
#define IDS_UNABLETOREMOVEDESKTOP       112
#define IDS_METHOD                      113
#define IDS_METHOD_HIDE                 114
#define IDS_METHOD_MINIMIZE             115
#define IDS_METHOD_MOVE                 116
#define IDS_DLGNAME_SETTINGS            117
#define IDS_SELECT_WALLPAPER            118
#define IDS_NOIMAGE                     119
#define IDS_DESKTOP_BASENAME            120
#define IDS_COLUMN_FUNCTION             121
#define IDS_COLUMN_SHORTCUT             122
#define IDS_MENU_ALWAYSONTOP            125
#define IDS_MENU_MINTOTRAY              126
#define IDS_MENU_TRANSPARENT            127
#define IDS_MENU_ONALLDESKTOPS          128
#define IDS_MENU_CHANGEDESKTOP          129
#define IDS_MENU_ACTIVATEWND            130
#define IDS_MENU_RESTOREWND             131
#define IDS_MENU_MINIMIZEWND            132
#define IDS_MENU_MAXIMIZEWND            133
#define IDS_MENU_MAXHEIGHTWND           134
#define IDS_MENU_MAXWIDTHWND            135
#define IDS_MENU_CLOSEWND               136
#define IDS_MENU_KILLWND                137
#define IDS_MENU_WNDPROPERTIES          138
#define IDS_AUTOSETTINGS_ERROR          139
#define IDS_WINDOWPROPERTIES            140
#define IDS_CONFIRMKILL                 141
#define IDS_KILLWARNING                 142
#define IDS_CONFIGURE                   148
#define IDS_LOCKPREVIEWWND              149
#define IDS_SHOWCAPTION                 150
#define IDS_ABOUT                       152
#define IDS_MENU_SIZE                   153
#define IDS_MENU_MOVE                   154
#define IDS_FLASH_MESSAGE               155
#define IDS_NO_SUCH_DESKTOP             156
#define IDS_CMDLINE_NOTANOPTION         157
#define IDS_CMDLINE_INVALIDOPTION       158
#define IDS_CMDLINE_MISSINGARG          159
#define IDS_CMDLINE_TITLE               160

// Controls
#define IDC_MYICON                      2
#define IDC_DESK_LIST                   1001
#define IDC_DESK_SPIN                   1002
#define IDC_INSERT_DESK                 1003
#define IDC_REMOVE_DESK                 1004
#define IDC_SETUP_DESK                  1005
#define IDC_COLUMN_NUMBER               1006
#define IDC_COLUMN_SPIN                 1007
#define IDC_APPLY                       1008
#define IDC_NAME                        1009
#define IDC_PREVIEW                     1010
#define IDC_CHOOSE_WALLPAPER            1011
#define IDC_HOTKEY                      1012
#define IDC_BGCOLOR_BTN                 1013
#define IDC_WALLPAPER                   1014
#define IDC_SHORTCUTSLIST               1015
#define IDC_TRANSP_SLIDER               1016
#define IDC_TRANSP_STATIC1              1017
#define IDC_TRANSP_STATIC2              1018
#define IDC_TRANSP_STATIC               1019
#define IDC_TRANSP_DISP                 1020
#define IDC_PLAINCOLOR_RATIO            1021
#define IDC_IMAGE_RATIO                 1022
#define IDC_SCREENSHOT_RATIO            1023
#define IDC_EXTRAPARAM_BTN              1024
#define IDC_FONT_BTN                    1025
#define IDC_ENABLEOSD_CHECK             1026
#define IDC_TIMEOUT_STATIC              1027
#define IDC_TIMEOUT_EDIT                1028
#define IDC_TIMEOUT_SPIN                1029
#define IDC_TRANSPARENT_CHK             1030
#define IDC_BACKGROUND_CHK              1031
#define IDC_POSITION_BTN                1032
#define IDC_ALLDESKS_CHECK              1033
#define IDC_ONTOP_CHECK                 1034
#define IDC_MINTOTRAY_CHECK             1035
#define IDC_ENABLETRANSP_CHECK          1036
#define IDC_DISABLE_RATIO               1037
#define IDC_LASTSESSION_RATIO           1038
#define IDC_SAVED_RATIO                 1039
#define IDC_SAVESETTINGS_BTN            1040
#define IDC_AUTOSIZE_CHECK              1041
#define IDC_AUTOPOS_CHECK               1042
#define IDC_AUTODESK_CHECK              1043
#define IDC_TRAYICON_CHECK              1050
#define IDC_TOOLTIPS_CHECK              1051
#define IDC_ALLWINDOWSINTASKLIST_CHECK  1052
#define IDC_CONFIRMKILL_CHECK           1053
#define IDC_CLOSETOTRAY_CHECK           1054
#define IDC_STARTWITHWINDOWS_CHECK      1055
#define IDC_AUTOSWITCHDESKTOP_CHECK     1056
#define IDC_SNAPSIZE_EDIT               1057
#define IDC_SNAPSIZE_SPIN               1058
#define IDC_AUTOHIDEDELAY_EDIT          1059
#define IDC_AUTOHIDEDELAY_SPIN          1060
#define IDC_MOUSEWARP_CHECK             1061
#define IDC_HIDEMETHOD_RADIO            1064
#define IDC_MINIMIZEMETHOD_RATIO        1065
#define IDC_MOVEMETHOD_RATIO            1066
#define IDC_HIDINGMETHODEXCEPTIONS_BTN  1067
#define IDC_APPL_LIST                   1069
#define IDC_INSERTAPPL_BTN              1070
#define IDC_EDITAPPL_BTN                1071
#define IDC_REMOVEAPPL_BTN              1072
#define IDC_PRODUCT                     1073
#define IDC_COPYRIGHT                   1074
#define IDC_BROWSE_WALLPAPER            1076
#define IDC_GPL_LINK                    1080
#define IDC_HOMEPAGE_LINK               1081
#define IDC_DEFAULT_WALLPAPER           1084
#define IDC_NO_WALLPAPER                1085
#define IDC_PREVIOUS_WALLPAPER          1086
#define IDC_CLEAR_SHORTCUT              1088
#define IDC_RESET_SHORTCUT              1089
#define IDC_MOUSEWARPCFG_BTN            1092
#define IDC_WARPSENSIBILITY_EDIT        1093
#define IDC_MINDURATION_EDIT            1094
#define IDC_REWARPDELAY_EDIT            1095
#define IDC_SWAPMOUSE_CHECK             1096
#define IDC_WARPKEY_NONE_RADIO          1097
#define IDC_WARPKEY_ALT_RADIO           1098
#define IDC_WARPKEY_SHIFT_RADIO         1099
#define IDC_WARPKEY_CTRL_RADIO          1100
#define IDC_WARPKEY_WIN_RADIO           1101
#define IDC_WARPKEY_OTHER_RADIO         1102
#define IDC_CUSTOMKEY_EDIT              1103
#define IDC_STATIC                      -1
